### ISSUE TITLE
Qt Material style not working as expected when app is bundled using PyInstaller

### ISSUE THREAD

**Issue by abrahampm** [abrahampm/histopathapp#2]
The issue occurs when I bundle the application using PyInstaller and execute the bundled application. Some kind of weird effect occurs in the menu when you click and hover the items in the menu. Images below show the problem.

![MaterialBug1](https://user-images.githubusercontent.com/59702400/98266829-bdfd2880-1f58-11eb-9a52-4615b4e348b7.png)
![MaterialBug2](https://user-images.githubusercontent.com/59702400/98266836-bfc6ec00-1f58-11eb-901d-ab1e72d6f00c.png)

However, executing the application with the Python interpreter, the Material Style is displayed as expected, as shown below.

![MaterialOk1](https://user-images.githubusercontent.com/59702400/98266591-80000480-1f58-11eb-8a32-cbf1f645765a.png)
![MaterialOk2](https://user-images.githubusercontent.com/59702400/98266610-842c2200-1f58-11eb-951a-f5651cc3e245.png)

This issue only occurs with Qt Material style, as when using the Default style the menu is displayed correctly, both from Python interpreter and bundled app. App with default style is shown below.

![DefaultOk2](https://user-images.githubusercontent.com/59702400/98268018-05d07f80-1f5a-11eb-9c4f-1696dc45d112.png)
![DefaultOk1](https://user-images.githubusercontent.com/59702400/98267999-fea97180-1f59-11eb-8b93-62f00584729f.png)

@lateo96 please take a look at this issue.

The application shows some warnings when executed, but I think is not related.
```
file:///App/venv/lib/python3.8/site-packages/PySide2/Qt/qml/QtQuick/Controls/TableViewColumn.qml:66:1: QML TableViewColumn: Accessible must be attached to an Item
file:///App/venv/lib/python3.8/site-packages/PySide2/Qt/qml/QtQuick/Controls/TableViewColumn.qml:66:1: QML TableViewColumn: Accessible must be attached to an Item
file:///App/venv/lib/python3.8/site-packages/PySide2/Qt/qml/QtQuick/Controls/TableViewColumn.qml:66:1: QML TableViewColumn: Accessible must be attached to an Item
file:///App/venv/lib/python3.8/site-packages/PySide2/Qt/qml/QtQuick/Controls/TableViewColumn.qml:66:1: QML TableViewColumn: Accessible must be attached to an Item
file:///App/venv/lib/python3.8/site-packages/PySide2/Qt/qml/QtQuick/Controls/TableViewColumn.qml:66:1: QML TableViewColumn: Accessible must be attached to an Item
file:///App/venv/lib/python3.8/site-packages/PySide2/Qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
file:///App/venv/lib/python3.8/site-packages/PySide2/Qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
```

**Comment by LateusBetelgeuse** [comment]
I suspect that the shaders are not properly deployed. Try importing the module Qt Graphical Effects in any QML document.

**Comment by abrahampm** [comment]
Ok, I tried adding `import QtGraphicalEffects 1.15` to the imports in main.qml. It did not fix the problem. Also noticed that PyInstaller is including Qt Graphical Effects plugin under `./dist/BreastHistopathApp/PySide2/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so`. Is there any way to debug this and see if there is any missing file or error during bundled app execution?
